### ISSUE TITLE
Placeholder Errors

### ISSUE THREAD

**Issue by murat716** [Fighter20000/basicboard#1]
**My Placeholders:**
%player_name%%vault_eco_balance%%townyadvanced_town%%townyadvanced_town_balance%
%townyadvanced_town_mayor%%townyadvanced_town_residents_online%%server_online%
%townyadvanced_town_residents_amount%%server_max_players%

**Error:**
[09:51:11 WARN]: [BasicBoard] Plugin BasicBoard v1.0 generated an exception while executing task 1021
java.lang.NumberFormatException: For input string: "20,03"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:549) ~[?:?]
	at BasicBoard.Placeholders.Placeholders.Colorize(Placeholders.java:24) ~[?:?]
	at BasicBoard.Manager.BoardManager.createBoardfor(BoardManager.java:42) ~[?:?]
	at BasicBoard.Manager.BoardManager$1.run(BoardManager.java:61) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-182]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.2.jar:git-Paper-182]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.2.jar:git-Paper-182]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]

**Paper: 1.16.2
BasicBoard: 1.0.0**

**Comment by vitya0717** [comment]
Can you send me your basicboard config?

**Comment by murat716** [comment]
[BasicBoard.zip](https://github.com/Fighter20000/basicboard/files/5174311/BasicBoard.zip)

**Comment by vitya0717** [comment]
Change your paper version to latest :) !
https://papermc.io/api/v1/paper/1.16.2/184/download

I have no idea what is this error, because on my 1.16.2(paper) server it working perfectly!

**Comment by vitya0717** [comment]
Try it:
[BasicBoard.zip](https://github.com/Fighter20000/basicboard/files/5174513/BasicBoard.zip)

**Comment by murat716** [comment]
Sorry i'm sended old config

`#BasicBoard v1.0
#
#Local varibales which working without PlaceholderAPI, I want to add more
#{player_name}
#{prefix} - (plugin prefix).
#{<worldname>_online_players} Online players in specific world'
#{player_ping}
#{player_world}
#{player_exp}
#{player_hp}
#{player_food}
#{player_kills}
#{player_deaths}
#{mob_kills}
#
#Vault placeholders: Needed vault for work!
#{player_balance}
#{player_group}
#{player_prefix}
#{player_suffix}
#
#
#FOR MORE PLACEHOLDERS https://github.com/Fighter20000/basicboard/wiki/Placeholders

#Recommended enable it, for lot of cool placeholders!
PlaceholderAPI:
  enable: true

BoardSettings:
  enable-board: true
  #time in tick, 20 tick = 1 second.
  scoreboard-update: 30
  #You can use prefix at anywhere with {prefix} variable
  board-prefix: "&9&lHaronken &9%server_online%&8/&9%server_max_players%"

#You can disable board in a specific world!
disable-worlds:
  - 'test'
  - 'exampleworld'

#Scoreboard header
scoreboard-displayname: '   &9&lHaronken &9%server_online%&8/&9%server_max_players%   '

#At this time you can't animate lines!
scoreboard:
  text:
    - ''
    - '&6&lOyuncu'
    - '  İsim: &6%player_name%'
    - '  Kese: &6%vault_eco_balance%⛃'
    - ''
    - '&6&lTowny'
    - '  Birlik: &6%townyadvanced_town%'
    - '  Banka: &6%townyadvanced_town_balance%⛃'
    - '  Başkan: &6%townyadvanced_town_mayor%'
    - '  Popülasyon: &7%townyadvanced_town_residents_online%/%townyadvanced_town_residents_amount%'
    - '                           '
    - '&7play.haronken.net '

`

i tried and it works thanks

**Comment by murat716** [comment]
My new issue is scoreboard shaking hmmm
